"""add ai latency and cost columns to ai_outputs

Revision ID: 7d9180214bee
Revises: 9c1f0b7c4a11
Create Date: 2026-04-11 12:30:01.440592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9180214bee'
down_revision: Union[str, None] = '9c1f0b7c4a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_outputs', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('ai_outputs', sa.Column('cost_estimate_gbp', sa.Numeric(precision=12, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_outputs', 'cost_estimate_gbp')
    op.drop_column('ai_outputs', 'latency_ms')
    # ### end Alembic commands ###
