"""
storage/models.py
==================
SQLAlchemy database models.
Every signal, order, fill, position, and decision is stored here.
This is the immutable audit log.
"""

from sqlalchemy import (
    Column,
    String,
    Numeric,
    DateTime,
    Boolean,
    Integer,
    JSON,
    Text,
    Index,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass


class SignalLog(Base):
    """Every signal generated by any strategy."""
    __tablename__ = "signals"

    id              = Column(String, primary_key=True)      # signal_id (UUID)
    timestamp       = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol          = Column(String(20), nullable=False, index=True)
    side            = Column(String(4), nullable=False)     # "buy" | "sell"
    strategy        = Column(String(50), nullable=False)
    confidence      = Column(Numeric(5, 4), nullable=False)
    asset_class     = Column(String(20), nullable=False)
    broker          = Column(String(20), nullable=False)
    news_score      = Column(Numeric(5, 4), nullable=True)
    news_veto       = Column(Boolean, default=False)
    metadata_       = Column("metadata", JSON, nullable=True)


class RiskLog(Base):
    """Every risk decision — approved and rejected."""
    __tablename__ = "risk_decisions"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    signal_id       = Column(String, nullable=False, index=True)
    timestamp       = Column(DateTime(timezone=True), nullable=False, index=True)
    verdict         = Column(String(10), nullable=False)    # "approved" | "rejected"
    reason          = Column(Text, nullable=False)
    checks_passed   = Column(JSON, nullable=True)
    checks_failed   = Column(JSON, nullable=True)


class OrderLog(Base):
    """Every order sent to a broker."""
    __tablename__ = "orders"

    id                  = Column(String, primary_key=True)  # client_order_id
    broker_order_id     = Column(String, nullable=True, index=True)
    signal_id           = Column(String, nullable=False, index=True)
    timestamp           = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol              = Column(String(20), nullable=False)
    side                = Column(String(4), nullable=False)
    order_type          = Column(String(20), nullable=False)
    quantity            = Column(Numeric(20, 8), nullable=False)
    limit_price         = Column(Numeric(20, 8), nullable=True)
    broker              = Column(String(20), nullable=False)
    status              = Column(String(20), nullable=False)
    filled_quantity     = Column(Numeric(20, 8), nullable=True)
    avg_fill_price      = Column(Numeric(20, 8), nullable=True)
    fee                 = Column(Numeric(20, 8), nullable=True)
    paper_mode          = Column(Boolean, default=True)


class PositionLog(Base):
    """Snapshot of positions at regular intervals."""
    __tablename__ = "positions"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    timestamp       = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol          = Column(String(20), nullable=False, index=True)
    broker          = Column(String(20), nullable=False)
    quantity        = Column(Numeric(20, 8), nullable=False)
    avg_entry_price = Column(Numeric(20, 8), nullable=False)
    current_price   = Column(Numeric(20, 8), nullable=False)
    unrealised_pnl  = Column(Numeric(20, 8), nullable=False)
    asset_class     = Column(String(20), nullable=False)


class PriceHistory(Base):
    """OHLCV candle data — TimescaleDB hypertable."""
    __tablename__ = "price_history"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    timestamp   = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol      = Column(String(20), nullable=False, index=True)
    timeframe   = Column(String(5), nullable=False)         # "1m", "5m", "1h", "1d"
    open        = Column(Numeric(20, 8), nullable=False)
    high        = Column(Numeric(20, 8), nullable=False)
    low         = Column(Numeric(20, 8), nullable=False)
    close       = Column(Numeric(20, 8), nullable=False)
    volume      = Column(Numeric(30, 8), nullable=False)
    broker      = Column(String(20), nullable=False)

    __table_args__ = (
        Index("ix_price_symbol_timeframe_ts", "symbol", "timeframe", "timestamp"),
    )


class DailyPnL(Base):
    """Daily P&L summary."""
    __tablename__ = "daily_pnl"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    date            = Column(String(10), nullable=False, index=True)    # "2026-04-04"
    realised_pnl    = Column(Numeric(20, 8), nullable=False, default=0)
    unrealised_pnl  = Column(Numeric(20, 8), nullable=False, default=0)
    total_fees      = Column(Numeric(20, 8), nullable=False, default=0)
    trade_count     = Column(Integer, nullable=False, default=0)
    portfolio_value = Column(Numeric(20, 8), nullable=False, default=0)
    strategy_breakdown = Column(JSON, nullable=True)


class FeatureSnapshot(Base):
    """
    M2 feature store: one row per OHLCV bar with computed technical features (JSON).
    Upsert on (symbol, timeframe, bar_timestamp).
    """

    __tablename__ = "feature_snapshots"
    __table_args__ = (
        UniqueConstraint(
            "symbol",
            "timeframe",
            "bar_timestamp",
            name="uq_feature_snapshots_symbol_tf_bar_ts",
        ),
        Index("ix_feature_symbol_tf_ts", "symbol", "timeframe", "bar_timestamp"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(32), nullable=False)
    timeframe = Column(String(8), nullable=False)
    bar_timestamp = Column(DateTime(timezone=True), nullable=False)
    open = Column(Numeric(20, 8), nullable=False)
    high = Column(Numeric(20, 8), nullable=False)
    low = Column(Numeric(20, 8), nullable=False)
    close = Column(Numeric(20, 8), nullable=False)
    volume = Column(Numeric(30, 8), nullable=False)
    features = Column(JSON, nullable=False)
    validation = Column(JSON, nullable=True)
    data_source = Column(String(20), nullable=False, default="yfinance")
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )


class NewsHeadline(Base):
    """M2 NewsAPI headlines; primary key = dedupe hash."""

    __tablename__ = "news_headlines"

    content_hash = Column(String(64), primary_key=True)
    url = Column(Text, nullable=False)
    title = Column(Text, nullable=False)
    description = Column(Text, nullable=True)
    source_name = Column(String(120), nullable=False)
    published_at = Column(DateTime(timezone=True), nullable=False, index=True)
    fetched_at = Column(DateTime(timezone=True), nullable=False)


class MacroObservation(Base):
    """M2 FRED series observations (e.g. FEDFUNDS, CPIAUCSL)."""

    __tablename__ = "macro_observations"
    __table_args__ = (
        UniqueConstraint("series_id", "obs_date", name="uq_macro_series_date"),
        Index("ix_macro_series_date", "series_id", "obs_date"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    series_id = Column(String(32), nullable=False)
    obs_date = Column(String(10), nullable=False)
    value = Column(Numeric(24, 10), nullable=False)
    fetched_at = Column(DateTime(timezone=True), nullable=False)


class ParameterLog(Base):
    """Audit trail for dynamic risk parameter changes."""

    __tablename__ = "parameter_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True, server_default=func.now())
    parameter = Column(String(64), nullable=False, index=True)
    layer = Column(String(20), nullable=False)  # regime | ai | ai_rejected | expiry
    old_value = Column(Numeric(20, 8), nullable=False)
    new_value = Column(Numeric(20, 8), nullable=False)
    reason = Column(Text, nullable=False)
    source = Column(String(50), nullable=False, default="system")
    confidence = Column(Numeric(5, 4), nullable=True)
    expiry_time = Column(DateTime(timezone=True), nullable=True)
    evidence = Column(JSON, nullable=True)


class AIOutputLog(Base):
    """Audit log for AI news/macro outputs used in signaling."""

    __tablename__ = "ai_outputs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True, server_default=func.now())
    symbol = Column(String(32), nullable=True, index=True)
    context_type = Column(String(20), nullable=False, index=True)  # news | macro | rationale
    score = Column(Numeric(10, 6), nullable=True)
    confidence = Column(Numeric(10, 6), nullable=True)
    event_type = Column(String(32), nullable=True)
    regime_label = Column(String(64), nullable=True)
    decay_hours = Column(Integer, nullable=True)
    rationale = Column(Text, nullable=True)
    payload = Column(JSON, nullable=True)
    source = Column(String(32), nullable=False, default="system")
    signal_id = Column(String(128), nullable=True, index=True)


class AnomalyLog(Base):
    __tablename__ = "anomaly_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    asset_class = Column(String(20), nullable=False)
    direction = Column(String(8), nullable=False)
    price_move_pct = Column(Numeric(10, 4), nullable=False)
    price_z_score = Column(Numeric(10, 4), nullable=False)
    volume_z_score = Column(Numeric(10, 4), nullable=True)
    news_velocity = Column(Numeric(10, 4), nullable=True)
    news_sentiment = Column(Numeric(10, 4), nullable=True)
    anomaly_score = Column(Numeric(10, 4), nullable=False)
    opportunities_found = Column(Integer, nullable=True)
    thesis_generated = Column(Boolean, default=False)
    signals_produced = Column(Integer, nullable=True)


class ThesisLog(Base):
    __tablename__ = "thesis_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)
    trigger_symbol = Column(String(20), nullable=False, index=True)
    trigger_direction = Column(String(8), nullable=False)
    trigger_explanation = Column(Text, nullable=False)
    overall_confidence = Column(Numeric(10, 4), nullable=False)
    time_horizon_hours = Column(Integer, nullable=False)
    opportunities = Column(JSON, nullable=True)
    invalidation_conditions = Column(JSON, nullable=True)
    model_used = Column(String(64), nullable=False)
    tokens_used = Column(Integer, nullable=True)
    ai_cost_usd = Column(Numeric(12, 6), nullable=True)


class ControlCommand(Base):
    """Cross-process control command queue for API -> runners."""

    __tablename__ = "control_commands"

    id = Column(Integer, primary_key=True, autoincrement=True)
    command_type = Column(String(64), nullable=False, index=True)  # kill | reset_kill | toggle_strategy | set_parameter
    payload = Column(JSON, nullable=True)
    status = Column(String(20), nullable=False, default="pending", index=True)  # pending | processing | done | failed
    created_at = Column(DateTime(timezone=True), nullable=False, index=True, server_default=func.now())
    claimed_at = Column(DateTime(timezone=True), nullable=True)
    processed_at = Column(DateTime(timezone=True), nullable=True)
    error = Column(Text, nullable=True)
    source = Column(String(32), nullable=False, default="api")


class ControlState(Base):
    """Key/value control plane state and runner heartbeats."""

    __tablename__ = "control_state"

    key = Column(String(128), primary_key=True)
    value = Column(JSON, nullable=True)
    updated_at = Column(DateTime(timezone=True), nullable=False, index=True, server_default=func.now(), onupdate=func.now())
