"""
storage/models.py
==================
SQLAlchemy database models.
Every signal, order, fill, position, and decision is stored here.
This is the immutable audit log.
"""

from datetime import datetime, timezone
from decimal import Decimal
from sqlalchemy import (
    Column, String, Numeric, DateTime, Boolean,
    Integer, JSON, Text, Index
)
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass


class SignalLog(Base):
    """Every signal generated by any strategy."""
    __tablename__ = "signals"

    id              = Column(String, primary_key=True)      # signal_id (UUID)
    timestamp       = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol          = Column(String(20), nullable=False, index=True)
    side            = Column(String(4), nullable=False)     # "buy" | "sell"
    strategy        = Column(String(50), nullable=False)
    confidence      = Column(Numeric(5, 4), nullable=False)
    asset_class     = Column(String(20), nullable=False)
    broker          = Column(String(20), nullable=False)
    news_score      = Column(Numeric(5, 4), nullable=True)
    news_veto       = Column(Boolean, default=False)
    metadata_       = Column("metadata", JSON, nullable=True)


class RiskLog(Base):
    """Every risk decision — approved and rejected."""
    __tablename__ = "risk_decisions"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    signal_id       = Column(String, nullable=False, index=True)
    timestamp       = Column(DateTime(timezone=True), nullable=False, index=True)
    verdict         = Column(String(10), nullable=False)    # "approved" | "rejected"
    reason          = Column(Text, nullable=False)
    checks_passed   = Column(JSON, nullable=True)
    checks_failed   = Column(JSON, nullable=True)


class OrderLog(Base):
    """Every order sent to a broker."""
    __tablename__ = "orders"

    id                  = Column(String, primary_key=True)  # client_order_id
    broker_order_id     = Column(String, nullable=True, index=True)
    signal_id           = Column(String, nullable=False, index=True)
    timestamp           = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol              = Column(String(20), nullable=False)
    side                = Column(String(4), nullable=False)
    order_type          = Column(String(20), nullable=False)
    quantity            = Column(Numeric(20, 8), nullable=False)
    limit_price         = Column(Numeric(20, 8), nullable=True)
    broker              = Column(String(20), nullable=False)
    status              = Column(String(20), nullable=False)
    filled_quantity     = Column(Numeric(20, 8), nullable=True)
    avg_fill_price      = Column(Numeric(20, 8), nullable=True)
    fee                 = Column(Numeric(20, 8), nullable=True)
    paper_mode          = Column(Boolean, default=True)


class PositionLog(Base):
    """Snapshot of positions at regular intervals."""
    __tablename__ = "positions"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    timestamp       = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol          = Column(String(20), nullable=False, index=True)
    broker          = Column(String(20), nullable=False)
    quantity        = Column(Numeric(20, 8), nullable=False)
    avg_entry_price = Column(Numeric(20, 8), nullable=False)
    current_price   = Column(Numeric(20, 8), nullable=False)
    unrealised_pnl  = Column(Numeric(20, 8), nullable=False)
    asset_class     = Column(String(20), nullable=False)


class PriceHistory(Base):
    """OHLCV candle data — TimescaleDB hypertable."""
    __tablename__ = "price_history"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    timestamp   = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol      = Column(String(20), nullable=False, index=True)
    timeframe   = Column(String(5), nullable=False)         # "1m", "5m", "1h", "1d"
    open        = Column(Numeric(20, 8), nullable=False)
    high        = Column(Numeric(20, 8), nullable=False)
    low         = Column(Numeric(20, 8), nullable=False)
    close       = Column(Numeric(20, 8), nullable=False)
    volume      = Column(Numeric(30, 8), nullable=False)
    broker      = Column(String(20), nullable=False)

    __table_args__ = (
        Index("ix_price_symbol_timeframe_ts", "symbol", "timeframe", "timestamp"),
    )


class DailyPnL(Base):
    """Daily P&L summary."""
    __tablename__ = "daily_pnl"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    date            = Column(String(10), nullable=False, index=True)    # "2026-04-04"
    realised_pnl    = Column(Numeric(20, 8), nullable=False, default=0)
    unrealised_pnl  = Column(Numeric(20, 8), nullable=False, default=0)
    total_fees      = Column(Numeric(20, 8), nullable=False, default=0)
    trade_count     = Column(Integer, nullable=False, default=0)
    portfolio_value = Column(Numeric(20, 8), nullable=False, default=0)
    strategy_breakdown = Column(JSON, nullable=True)
