"""
storage/models.py
==================
SQLAlchemy database models.
Every signal, order, fill, position, and decision is stored here.
This is the immutable audit log.
"""

from sqlalchemy import (
    Column,
    String,
    Numeric,
    DateTime,
    Boolean,
    Integer,
    JSON,
    Text,
    Index,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass


class SignalLog(Base):
    """Every signal generated by any strategy."""
    __tablename__ = "signals"

    id              = Column(String, primary_key=True)      # signal_id (UUID)
    timestamp       = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol          = Column(String(72), nullable=False, index=True)
    side            = Column(String(4), nullable=False)     # "buy" | "sell"
    strategy        = Column(String(50), nullable=False)
    confidence      = Column(Numeric(5, 4), nullable=False)
    asset_class     = Column(String(20), nullable=False)
    broker          = Column(String(20), nullable=False)
    news_score      = Column(Numeric(5, 4), nullable=True)
    news_veto       = Column(Boolean, default=False)
    metadata_       = Column("metadata", JSON, nullable=True)


class RiskLog(Base):
    """Every risk decision — approved and rejected."""
    __tablename__ = "risk_decisions"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    signal_id       = Column(String, nullable=False, index=True)
    timestamp       = Column(DateTime(timezone=True), nullable=False, index=True)
    verdict         = Column(String(10), nullable=False)    # "approved" | "rejected"
    reason          = Column(Text, nullable=False)
    checks_passed   = Column(JSON, nullable=True)
    checks_failed   = Column(JSON, nullable=True)


class OrderLog(Base):
    """Every order sent to a broker."""
    __tablename__ = "orders"

    id                  = Column(String, primary_key=True)  # client_order_id
    broker_order_id     = Column(String, nullable=True, index=True)
    signal_id           = Column(String, nullable=False, index=True)
    timestamp           = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol              = Column(String(72), nullable=False)
    side                = Column(String(4), nullable=False)
    order_type          = Column(String(20), nullable=False)
    quantity            = Column(Numeric(20, 8), nullable=False)
    limit_price         = Column(Numeric(20, 8), nullable=True)
    broker              = Column(String(20), nullable=False)
    status              = Column(String(20), nullable=False)
    filled_quantity     = Column(Numeric(20, 8), nullable=True)
    avg_fill_price      = Column(Numeric(20, 8), nullable=True)
    fee                 = Column(Numeric(20, 8), nullable=True)
    paper_mode          = Column(Boolean, default=True)
    instrument_metadata = Column(JSON, nullable=True)


class FillLog(Base):
    """D126 — clean append-only ledger of confirmed fills.

    One row per confirmed fill. Unlike ``orders`` (an order-lifecycle
    log that also holds cancelled / rejected states and is contaminated
    by the pre-D126 phantom-oversell bug), this table is BOTH the
    authoritative analytics ledger and the race-free source of truth
    for position quantity: a position's quantity for ``(broker, symbol)``
    is ``SUM(signed_quantity)`` over its fills. Pure appends never
    conflict, so the snapshot-resurrection race that produced phantom
    oversells cannot occur here.

    Every confirmed fill writes exactly one row. ``realised_pnl`` and
    ``holding_period_sec`` are populated only on position-decreasing
    (closing) fills, computed via weighted-average cost basis.
    """
    __tablename__ = "fills"
    __table_args__ = (
        Index("ix_fills_broker_symbol_ts", "broker", "symbol", "timestamp"),
    )

    id                  = Column(Integer, primary_key=True, autoincrement=True)
    timestamp           = Column(DateTime(timezone=True), nullable=False, index=True)
    broker              = Column(String(20), nullable=False, index=True)
    symbol              = Column(String(72), nullable=False, index=True)
    asset_class         = Column(String(20), nullable=False, default="")
    side                = Column(String(8), nullable=False)            # buy / sell
    order_type          = Column(String(20), nullable=False, default="")
    quantity            = Column(Numeric(20, 8), nullable=False)       # absolute filled qty
    signed_quantity     = Column(Numeric(20, 8), nullable=False)       # +buy / -sell; position qty = SUM(this)
    fill_price          = Column(Numeric(20, 8), nullable=False)
    notional            = Column(Numeric(20, 8), nullable=False, default=0)
    fee                 = Column(Numeric(20, 8), nullable=False, default=0)
    # D130 — execution-quality capture. ``intended_price`` is the signal's
    # target price (``signal.suggested_price``) known at order time;
    # ``slippage_bps`` is signed adverse slippage = positive when the fill
    # was WORSE than intended (a cost), negative on price improvement.
    # Both NULL when no intended price was available (cannot be backfilled
    # onto pre-D130 fills — only forward-captured fills carry it).
    intended_price      = Column(Numeric(20, 8), nullable=True)
    slippage_bps        = Column(Numeric(12, 4), nullable=True)
    reduce_only         = Column(Boolean, nullable=False, default=False)
    # Realised P&L (weighted-average cost). Non-zero only on closing
    # (position-decreasing) fills.
    realised_pnl        = Column(Numeric(20, 8), nullable=False, default=0)
    avg_cost_basis      = Column(Numeric(20, 8), nullable=True)        # WAC of the position at fill time
    position_qty_after  = Column(Numeric(20, 8), nullable=False)       # signed position qty after this fill
    holding_period_sec  = Column(Numeric(20, 2), nullable=True)        # lot age when closed (closing fills only)
    # Strategy / signal context
    strategy            = Column(String(64), nullable=True, index=True)
    signal_id           = Column(String, nullable=True, index=True)
    signal_confidence   = Column(Numeric(10, 6), nullable=True)
    mode                = Column(String(16), nullable=True)            # hunter / trader / defender
    # Audit / reconciliation
    is_paper            = Column(Boolean, nullable=False, default=True)
    run_session_id      = Column(String(40), nullable=True, index=True)
    derisk_source       = Column(String(32), nullable=True)            # intraday_derisk / aggregate_derisk / stop_loss / profit_harvest
    order_id            = Column(String, nullable=True, index=True)    # links to orders.id
    broker_order_id     = Column(String, nullable=True)
    instrument_metadata = Column(JSON, nullable=True)


class PositionLog(Base):
    """Snapshot of positions at regular intervals."""
    __tablename__ = "positions"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    timestamp       = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol          = Column(String(72), nullable=False, index=True)
    broker          = Column(String(20), nullable=False)
    quantity        = Column(Numeric(20, 8), nullable=False)
    avg_entry_price = Column(Numeric(20, 8), nullable=False)
    current_price   = Column(Numeric(20, 8), nullable=False)
    unrealised_pnl  = Column(Numeric(20, 8), nullable=False)
    asset_class     = Column(String(20), nullable=False)
    instrument_metadata = Column(JSON, nullable=True)


class ConnectorState(Base):
    """D127 Connect Hub v2 — per-install connector lifecycle state.

    `config/connectors.yaml` is the static, version-controlled *catalogue*
    of supported connectors. This table is the per-install *state* layer:
    which catalogue connectors this operator has set up, their lifecycle
    status, the result of the last live capability test, the capabilities
    actually detected (vs merely declared in the manifest), and AI-stage
    version / install metadata. Secrets never live here — they stay in
    `.env`. One install = one operator, so no user dimension.
    """
    __tablename__ = "connector_state"
    __table_args__ = (
        UniqueConstraint("category", "connector_id", name="uq_connector_state_cat_id"),
    )

    id                        = Column(Integer, primary_key=True, autoincrement=True)
    category                  = Column(String(32), nullable=False)   # brokers / information_feeds / ai_providers / treasury_accounts
    connector_id              = Column(String(64), nullable=False)
    status                    = Column(String(32), nullable=False, default="not_configured")
    enabled                   = Column(Boolean, nullable=False, default=False)
    certification_tier        = Column(String(16), nullable=True)    # certified / experimental
    last_test_at              = Column(DateTime(timezone=True), nullable=True)
    last_test_result          = Column(JSON, nullable=True)          # {ok, reason, latency_ms, ...}
    detected_capabilities     = Column(JSON, nullable=True)          # {can_trade: true, can_read_balance: true, ...}
    # AI-stage fields (populated in P3/P4 — nullable so no later migration).
    ai_model_version          = Column(String(64), nullable=True)
    local_model_install_state = Column(String(32), nullable=True)    # installed / available / unsupported / too_slow
    machine_probe             = Column(JSON, nullable=True)          # {cpu, ram_gb, gpu, vram_gb, ...}
    updated_at                = Column(DateTime(timezone=True), nullable=False)


class PriceHistory(Base):
    """OHLCV candle data — TimescaleDB hypertable."""
    __tablename__ = "price_history"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    timestamp   = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol      = Column(String(20), nullable=False, index=True)
    timeframe   = Column(String(5), nullable=False)         # "1m", "5m", "1h", "1d"
    open        = Column(Numeric(20, 8), nullable=False)
    high        = Column(Numeric(20, 8), nullable=False)
    low         = Column(Numeric(20, 8), nullable=False)
    close       = Column(Numeric(20, 8), nullable=False)
    volume      = Column(Numeric(30, 8), nullable=False)
    broker      = Column(String(20), nullable=False)

    __table_args__ = (
        Index("ix_price_symbol_timeframe_ts", "symbol", "timeframe", "timestamp"),
    )


class DailyPnL(Base):
    """Daily P&L summary."""
    __tablename__ = "daily_pnl"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    date            = Column(String(10), nullable=False, index=True)    # "2026-04-04"
    realised_pnl    = Column(Numeric(20, 8), nullable=False, default=0)
    unrealised_pnl  = Column(Numeric(20, 8), nullable=False, default=0)
    total_fees      = Column(Numeric(20, 8), nullable=False, default=0)
    trade_count     = Column(Integer, nullable=False, default=0)
    portfolio_value = Column(Numeric(20, 8), nullable=False, default=0)
    strategy_breakdown = Column(JSON, nullable=True)


class FeatureSnapshot(Base):
    """
    M2 feature store: one row per OHLCV bar with computed technical features (JSON).
    Upsert on (symbol, timeframe, bar_timestamp).
    """

    __tablename__ = "feature_snapshots"
    __table_args__ = (
        UniqueConstraint(
            "symbol",
            "timeframe",
            "bar_timestamp",
            name="uq_feature_snapshots_symbol_tf_bar_ts",
        ),
        Index("ix_feature_symbol_tf_ts", "symbol", "timeframe", "bar_timestamp"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(32), nullable=False)
    timeframe = Column(String(8), nullable=False)
    bar_timestamp = Column(DateTime(timezone=True), nullable=False)
    open = Column(Numeric(20, 8), nullable=False)
    high = Column(Numeric(20, 8), nullable=False)
    low = Column(Numeric(20, 8), nullable=False)
    close = Column(Numeric(20, 8), nullable=False)
    volume = Column(Numeric(30, 8), nullable=False)
    features = Column(JSON, nullable=False)
    validation = Column(JSON, nullable=True)
    data_source = Column(String(20), nullable=False, default="yfinance")
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )


class NewsHeadline(Base):
    """M2 NewsAPI headlines; primary key = dedupe hash."""

    __tablename__ = "news_headlines"

    content_hash = Column(String(64), primary_key=True)
    url = Column(Text, nullable=False)
    title = Column(Text, nullable=False)
    description = Column(Text, nullable=True)
    source_name = Column(String(120), nullable=False)
    # Pipeline key (newsapi, finnhub, …) for per-feed “latest headline” age on the dashboard.
    ingest_provider = Column(String(32), nullable=True, index=True)
    published_at = Column(DateTime(timezone=True), nullable=False, index=True)
    fetched_at = Column(DateTime(timezone=True), nullable=False)


class MacroObservation(Base):
    """M2 FRED series observations (e.g. FEDFUNDS, CPIAUCSL)."""

    __tablename__ = "macro_observations"
    __table_args__ = (
        UniqueConstraint("series_id", "obs_date", name="uq_macro_series_date"),
        Index("ix_macro_series_date", "series_id", "obs_date"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    series_id = Column(String(32), nullable=False)
    obs_date = Column(String(10), nullable=False)
    value = Column(Numeric(24, 10), nullable=False)
    fetched_at = Column(DateTime(timezone=True), nullable=False)


class ParameterLog(Base):
    """Audit trail for dynamic risk parameter changes."""

    __tablename__ = "parameter_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True, server_default=func.now())
    parameter = Column(String(64), nullable=False, index=True)
    layer = Column(String(20), nullable=False)  # regime | ai | ai_rejected | expiry
    old_value = Column(Numeric(20, 8), nullable=False)
    new_value = Column(Numeric(20, 8), nullable=False)
    reason = Column(Text, nullable=False)
    source = Column(String(50), nullable=False, default="system")
    confidence = Column(Numeric(5, 4), nullable=True)
    expiry_time = Column(DateTime(timezone=True), nullable=True)
    evidence = Column(JSON, nullable=True)


class AIOutputLog(Base):
    """Audit log for AI news/macro outputs used in signaling."""

    __tablename__ = "ai_outputs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True, server_default=func.now())
    symbol = Column(String(32), nullable=True, index=True)
    context_type = Column(String(20), nullable=False, index=True)  # news | macro | rationale
    score = Column(Numeric(10, 6), nullable=True)
    confidence = Column(Numeric(10, 6), nullable=True)
    event_type = Column(String(32), nullable=True)
    regime_label = Column(String(64), nullable=True)
    decay_hours = Column(Integer, nullable=True)
    rationale = Column(Text, nullable=True)
    payload = Column(JSON, nullable=True)
    source = Column(String(32), nullable=False, default="system")
    signal_id = Column(String(128), nullable=True, index=True)
    latency_ms = Column(Integer, nullable=True)
    cost_estimate_gbp = Column(Numeric(12, 6), nullable=True)


class AnomalyLog(Base):
    __tablename__ = "anomaly_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    asset_class = Column(String(20), nullable=False)
    direction = Column(String(8), nullable=False)
    price_move_pct = Column(Numeric(10, 4), nullable=False)
    price_z_score = Column(Numeric(10, 4), nullable=False)
    volume_z_score = Column(Numeric(10, 4), nullable=True)
    news_velocity = Column(Numeric(10, 4), nullable=True)
    news_sentiment = Column(Numeric(10, 4), nullable=True)
    anomaly_score = Column(Numeric(10, 4), nullable=False)
    opportunities_found = Column(Integer, nullable=True)
    thesis_generated = Column(Boolean, default=False)
    signals_produced = Column(Integer, nullable=True)


class ThesisLog(Base):
    __tablename__ = "thesis_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)
    trigger_symbol = Column(String(20), nullable=False, index=True)
    trigger_direction = Column(String(8), nullable=False)
    trigger_explanation = Column(Text, nullable=False)
    overall_confidence = Column(Numeric(10, 4), nullable=False)
    time_horizon_hours = Column(Integer, nullable=False)
    opportunities = Column(JSON, nullable=True)
    invalidation_conditions = Column(JSON, nullable=True)
    model_used = Column(String(64), nullable=False)
    tokens_used = Column(Integer, nullable=True)
    ai_cost_usd = Column(Numeric(12, 6), nullable=True)


class ControlCommand(Base):
    """Cross-process control command queue for API -> runners."""

    __tablename__ = "control_commands"

    id = Column(Integer, primary_key=True, autoincrement=True)
    command_type = Column(String(64), nullable=False, index=True)  # kill | reset_kill | toggle_strategy | set_parameter
    payload = Column(JSON, nullable=True)
    status = Column(String(20), nullable=False, default="pending", index=True)  # pending | processing | done | failed
    created_at = Column(DateTime(timezone=True), nullable=False, index=True, server_default=func.now())
    claimed_at = Column(DateTime(timezone=True), nullable=True)
    processed_at = Column(DateTime(timezone=True), nullable=True)
    error = Column(Text, nullable=True)
    source = Column(String(32), nullable=False, default="api")


class ControlState(Base):
    """Key/value control plane state and runner heartbeats."""

    __tablename__ = "control_state"

    key = Column(String(128), primary_key=True)
    value = Column(JSON, nullable=True)
    updated_at = Column(DateTime(timezone=True), nullable=False, index=True, server_default=func.now(), onupdate=func.now())


class FeatureContract(Base):
    """Frozen feature list used by a trained model. Wave 1.

    The ``hash`` column is a deterministic SHA-256 over the canonical
    feature list (see ``models.feature_contracts.compute_feature_hash``).
    Multiple model versions can share a contract; we never mutate one in
    place.
    """

    __tablename__ = "feature_contracts"

    hash = Column(String(64), primary_key=True)
    feature_list = Column(JSON, nullable=False)
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    notes = Column(Text, nullable=True)


class TrainingDataset(Base):
    """Pointer to the dataset snapshot used to train a model. Wave 1."""

    __tablename__ = "training_datasets"
    __table_args__ = (
        UniqueConstraint("name", "version", name="uq_training_datasets_name_version"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(128), nullable=False, index=True)
    version = Column(String(32), nullable=False)
    start_ts = Column(DateTime(timezone=True), nullable=False)
    end_ts = Column(DateTime(timezone=True), nullable=False)
    row_count = Column(Integer, nullable=True)
    feature_contract_hash = Column(String(64), nullable=True, index=True)
    metadata_ = Column("metadata", JSON, nullable=True)
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )


class ModelVersion(Base):
    """Registered, immutable model artefact. Wave 1.

    A model may not influence live trading until a row exists here with
    ``approval_status in ('paper','micro_live','live')`` and the matching
    entry in ``config/model_registry.yaml``.
    """

    __tablename__ = "model_versions"
    __table_args__ = (
        UniqueConstraint("name", "version", name="uq_model_versions_name_version"),
        Index("ix_model_versions_name_status", "name", "approval_status"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(128), nullable=False, index=True)
    version = Column(String(32), nullable=False)
    task = Column(String(32), nullable=False)  # classification | regression
    target = Column(String(128), nullable=False)
    horizon_seconds = Column(Integer, nullable=True)
    horizon_bars = Column(Integer, nullable=True)
    feature_contract_hash = Column(String(64), nullable=False, index=True)
    training_dataset_id = Column(Integer, nullable=True, index=True)
    validation_method = Column(String(64), nullable=False)
    calibration_method = Column(String(32), nullable=False, default="none")
    min_sample_size = Column(Integer, nullable=False, default=0)
    approval_status = Column(
        String(20),
        nullable=False,
        default="research",
        index=True,
    )  # research | paper | micro_live | live | retired
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    created_by = Column(String(64), nullable=False, default="system")
    notes = Column(Text, nullable=True)
    metadata_ = Column("metadata", JSON, nullable=True)


class ModelRun(Base):
    """One row per training or evaluation invocation. Wave 1."""

    __tablename__ = "model_runs"
    __table_args__ = (
        Index("ix_model_runs_name_version_kind", "model_name", "model_version", "kind"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    model_name = Column(String(128), nullable=False, index=True)
    model_version = Column(String(32), nullable=False)
    kind = Column(String(16), nullable=False)  # train | eval
    status = Column(String(16), nullable=False, default="running")  # running | succeeded | failed
    started_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    finished_at = Column(DateTime(timezone=True), nullable=True)
    metrics = Column(JSON, nullable=True)
    notes = Column(Text, nullable=True)


class ModelPrediction(Base):
    """One row per live/paper/research prediction emitted by a registered model. Wave 1.

    ``as_of_ts`` is the latest feature timestamp used to compute the
    prediction. ``prediction_ts`` is when the model was invoked.
    ``as_of_ts <= prediction_ts`` is a hard invariant — future-stamped
    rows are rejected by ``models.prediction_store.write_prediction``.
    """

    __tablename__ = "model_predictions"
    __table_args__ = (
        Index(
            "ix_model_pred_name_version_ts",
            "model_name",
            "model_version",
            "prediction_ts",
        ),
        Index("ix_model_pred_symbol_ts", "symbol", "prediction_ts"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    model_name = Column(String(128), nullable=False, index=True)
    model_version = Column(String(32), nullable=False)
    symbol = Column(String(72), nullable=False, index=True)
    as_of_ts = Column(DateTime(timezone=True), nullable=False)
    prediction_ts = Column(DateTime(timezone=True), nullable=False)
    horizon_seconds = Column(Integer, nullable=True)
    horizon_bars = Column(Integer, nullable=True)
    predicted_probability = Column(Numeric(10, 8), nullable=True)
    expected_return = Column(Numeric(20, 10), nullable=True)
    expected_volatility = Column(Numeric(20, 10), nullable=True)
    confidence = Column(Numeric(10, 8), nullable=True)
    feature_hash = Column(String(64), nullable=False, index=True)
    mode = Column(String(16), nullable=False, default="research")  # research | paper | live
    metadata_ = Column("metadata", JSON, nullable=True)


class StrategyCandidateLog(Base):
    """Pre-execution strategy attempts: not the same as ``SignalLog`` (execution-bound).

    One row per raw or skip event so operators can see regime/meta filters and
    multi-strategy competition without polluting ``signals``/meta_adaptation joins.
    """

    __tablename__ = "strategy_candidate_log"

    id = Column(String(40), primary_key=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)
    loop_iteration = Column(Integer, nullable=True, index=True)
    symbol = Column(String(72), nullable=False, index=True)
    strategy = Column(String(50), nullable=False, index=True)
    side = Column(String(8), nullable=True)
    confidence = Column(Numeric(12, 6), nullable=True)
    adjusted_strength = Column(Numeric(20, 8), nullable=True)
    status = Column(
        String(40),
        nullable=False,
        index=True,
    )  # batched | filtered_regime | filtered_meta | skipped_event_driven_no_ai | raw_to_candidate_failed
    reason = Column(Text, nullable=True)
    winner_strategy = Column(String(50), nullable=True)
    metadata_ = Column("metadata", JSON, nullable=True)


class InstrumentRegistry(Base):
    """Canonical instrument master populated from public maintained sources.

    A row exists per ``canonical_symbol`` (yfinance form). Sources contribute
    via ``InstrumentSourceMembership``; per-broker tradeability is tracked in
    ``InstrumentBrokerAvailability``. Retirement is soft (``retired_at`` set)
    and requires multi-source consensus that the symbol is gone.
    """

    __tablename__ = "instrument_registry"

    canonical_symbol = Column(String(72), primary_key=True)
    display_name = Column(String(255), nullable=True)
    asset_class = Column(String(20), nullable=False, index=True)  # equity|etf|crypto|fx|future|bond|index
    region = Column(String(16), nullable=True, index=True)        # US|EU|UK|JP|HK|AU|CA|Global
    exchange = Column(String(32), nullable=True)
    currency = Column(String(8), nullable=True)
    sector = Column(String(64), nullable=True)
    industry = Column(String(64), nullable=True)
    isin = Column(String(16), nullable=True, index=True)
    figi = Column(String(16), nullable=True, index=True)
    first_seen_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    last_seen_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    last_refreshed_at = Column(DateTime(timezone=True), nullable=True)
    retired_at = Column(DateTime(timezone=True), nullable=True, index=True)
    metadata_ = Column("metadata", JSON, nullable=True)


class InstrumentSourceMembership(Base):
    """Per-source contribution to ``InstrumentRegistry``.

    Composite key ``(canonical_symbol, source_id)`` lets the same symbol be
    contributed by multiple independent sources (e.g. S&P 500 from Wikipedia
    AND iShares IVV). ``consecutive_miss_count`` is incremented each refresh
    where the source did not include the symbol; the retire policy compares
    misses across multiple sources before flagging ``InstrumentRegistry``.
    """

    __tablename__ = "instrument_source_membership"
    __table_args__ = (
        Index("ix_instrument_source_membership_source", "source_id"),
        Index(
            "ix_instrument_source_membership_symbol_source",
            "canonical_symbol",
            "source_id",
            unique=True,
        ),
    )

    canonical_symbol = Column(String(72), primary_key=True)
    source_id = Column(String(64), primary_key=True)
    source_version = Column(String(32), nullable=True)
    external_id = Column(String(64), nullable=True)  # vendor-specific ID e.g. iShares fund row id
    last_seen_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    consecutive_miss_count = Column(Integer, nullable=False, default=0)
    metadata_ = Column("metadata", JSON, nullable=True)


class InstrumentBrokerAvailability(Base):
    """Per-(symbol, broker) availability resolution.

    ``status`` values:
      - ``unknown`` (not evaluated yet)
      - ``available`` (broker catalog confirms tradeable)
      - ``unavailable`` (catalog does not contain a translation)
      - ``requires_qualification`` (IBKR-only: needs contract qualification before order)
      - ``blocked`` (operator override)
    Never deleted; transitions only. ``broker_symbol`` holds the broker-native
    string used for routing.
    """

    __tablename__ = "instrument_broker_availability"
    __table_args__ = (
        Index("ix_instrument_broker_availability_broker", "broker"),
        Index("ix_instrument_broker_availability_status", "status"),
    )

    canonical_symbol = Column(String(72), primary_key=True)
    broker = Column(String(20), primary_key=True)
    broker_symbol = Column(String(72), nullable=True)
    status = Column(String(32), nullable=False, default="unknown")
    last_checked_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    last_available_at = Column(DateTime(timezone=True), nullable=True)
    qualification_payload = Column(JSON, nullable=True)
    last_error = Column(Text, nullable=True)


class InstrumentSourceRun(Base):
    """Append-only audit row per source-refresh attempt.

    Captures rows added/updated/missing and the overall outcome so operators
    can answer 'when did Wikipedia last successfully ingest the S&P 500?'
    without inspecting logs.
    """

    __tablename__ = "instrument_source_runs"
    __table_args__ = (
        Index("ix_instrument_source_runs_source_started", "source_id", "started_at"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    source_id = Column(String(64), nullable=False, index=True)
    started_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    finished_at = Column(DateTime(timezone=True), nullable=True)
    status = Column(String(16), nullable=False, default="running")  # running|success|partial|failed
    rows_added = Column(Integer, nullable=True)
    rows_updated = Column(Integer, nullable=True)
    rows_missing = Column(Integer, nullable=True)
    notes = Column(Text, nullable=True)
    error = Column(Text, nullable=True)
